name: pyre

on:
  [push, pull_request]
jobs:
  pyre:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install .
          python3 -m pip install docopt schema psutil setuptools
          VERSION=$(grep "version" .pyre_configuration | sed -n -e 's/.*\(0\.0\.[0-9]*\).*/\1/p')
          python3 -m pip install pyre-check-nightly==$VERSION
          python3 -m pip show docopt
          python3 -m pip show psutil
      - name: Run Pyre
        run: |
          pyre check
